# Project identification
sonar.projectKey=Neo-4-Flix
sonar.projectName=Neo-4-Flix
sonar.projectVersion=1.0

# Source directories
sonar.sources=services,frontend/src
sonar.java.binaries=services/**/target/classes
sonar.java.libraries=**/target/dependency/*.jar

# Exclusions (we don't scan dependencies or builds)
sonar.exclusions=frontend/node_modules/**,**/target/**,frontend/dist/**

# Test directories and inclusions
sonar.tests=services/movie-service/src/test,services/user-service/src/test,frontend/src
sonar.test.inclusions=**/*.spec.ts,**/*Test.java

# Coverage report paths
sonar.javascript.lcov.reportPaths=frontend/coverage/frontend/lcov.info
sonar.typescript.lcov.reportPaths=frontend/coverage/frontend/lcov.info
sonar.coverage.jacoco.xmlReportPaths=services/movie-service/target/site/jacoco/jacoco.xml,services/user-service/target/site/jacoco/jacoco.xml
