# Project identification
sonar.projectKey=Neo-4-Flix
sonar.projectName=Neo-4-Flix
sonar.projectVersion=1.0

# Source directories
sonar.sources=services,frontend/src
sonar.java.binaries=services/**/target/classes
sonar.java.libraries=**/target/dependency/*.jar

# Exclusions (we don't scan dependencies or builds)
sonar.exclusions=frontend/node_modules/**,**/target/**,frontend/dist/**
