# Project identification
sonar.projectKey=Neo-4-Flix
sonar.projectName=Neo-4-Flix
sonar.projectVersion=1.0

# Exclusions glob pattern for multiple things
sonar.exclusions=frontend/node_modules/**,**/target/**,frontend/dist/**

#Exclusions for duplications (CPD)
sonar.cpd.exclusions=**/SecurityConfig.java, **/JwtUtil.java, **/JwtAuthFilter.java

# Define separate modules so SonarQube segregates coverage correctly
sonar.modules=frontend,user-service,movie-service,rating-service

# --- Frontend Module ---
frontend.sonar.projectBaseDir=frontend
frontend.sonar.sources=src
frontend.sonar.tests=src
frontend.sonar.test.inclusions=**/*.spec.ts
frontend.sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info
frontend.sonar.typescript.lcov.reportPaths=coverage/frontend/lcov.info

# --- User Service Module ---
user-service.sonar.projectBaseDir=services/user-service
user-service.sonar.sources=src/main/java
user-service.sonar.tests=src/test/java
user-service.sonar.java.binaries=target/classes
user-service.sonar.java.libraries=target/dependency/*.jar
user-service.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# --- Movie Service Module ---
movie-service.sonar.projectBaseDir=services/movie-service
movie-service.sonar.sources=src/main/java
movie-service.sonar.tests=src/test/java
movie-service.sonar.java.binaries=target/classes
movie-service.sonar.java.libraries=target/dependency/*.jar
movie-service.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# --- Rating Service Module ---
rating-service.sonar.projectBaseDir=services/rating-service
rating-service.sonar.sources=src/main/java
rating-service.sonar.tests=src/test/java
rating-service.sonar.java.binaries=target/classes
rating-service.sonar.java.libraries=target/dependency/*.jar
rating-service.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
